### ISSUE TITLE
Makefile error / Help Needed

### ISSUE THREAD

**Issue by AmdEagle** [brion/jsdec-openh264#1]
Do you have an updated version of the h264-decoder.js ?
I am trying project where i need to take in h264( Main profile ) byte stream array of stream from websocket and display / play it on a canvas. And i was trying our your project.

i am getting this error when i try to emscripten the h264-decoder.cpp
![image](https://cloud.githubusercontent.com/assets/6722962/23014452/ff9dc3e4-f469-11e6-8bcc-2f922413be4b.png)

Do you have any latest version that you have which will be great help to me. Or any guidance or any direction that i need to take as i would help me out a lot i have been taking a crack at this for almost 2 weeks and i dont seem to be getting anywhere.. I am pretty new to this emscripten library too.

**Comment by bvibber** [comment]
I haven't updated it no; there may have been changes to the OpenH264
interfaces in the meantime. Will take a peek this weekend and see if can
update it to work with a current build and make the module callable more
easily.

For display you may also want https://github.com/brion/yuv-canvas which I
use in my Ogg/webm player  https://github.com/brion/ogv.js

**Comment by AmdEagle** [comment]
Thank you very much. It would be so much help to me.
How do i use your yuv-canvas if i receive a array of yuv data from a decoder.

Thanks again.

**Comment by AmdEagle** [comment]
Hi any update on the h264-decoder.js build ?

**Comment by bvibber** [comment]
This should fix the build with current OpenH264: https://github.com/brion/jsdec-openh264/commit/d1471c83098ea149c722bcb1e85192c56e472410

Turns out just had to remove the color output setting, since that setting seems to have been removed.

**Comment by AmdEagle** [comment]
I am sorry i am not able to create a js version of the decoder another error poped up would be able to compile and upload a js verison of the decoder ?

Error encountered 
![image](https://cloud.githubusercontent.com/assets/6722962/23495127/ed7f8038-ff51-11e6-8c42-7771755a11a5.png)

**Comment by bvibber** [comment]
It looks like an internal emscripten error? It's failing on compilation of something in the C standard library.
